group_dynamics = {
    "Analysts": {
        "color": "#b489fa",
        "icon": "◆",
        "members": ["Paula Lopez", "Mica Dwyer", "Hiromi Masaki", "Gillian Wiley"],
        "mbti_types": ["INTP", "ENTP", "INTJ", "ENTJ"],
        "tagline": "They don't hang out. They convene.",
        "facts": [
            "Lowkey — and by lowkey, aggressively — obsessed with Hayami. No one will admit it.",
            "They argue for sport. Mica starts it. Paula corrects it. Hiromi refines it. Gillian ends it.",
            "If left unsupervised they will turn a casual discussion into a 4-hour meta-analysis of power scalability.",
            "They respect the Explorers' instinctive intelligence more than they will ever admit.",
            "Secret fear: being out-thought by someone who didn't plan for it.",
        ],
        "strengths": "Abstract strategy, theoretical frameworks, long-term planning",
        "weakness": "Emotional disruption, overanalyzing simple problems",
        "chaos_rating": "3 / 10 — Controlled. Intentional. Terrifying.",
    },
    "Explorers": {
        "color": "#ffd000",
        "icon": "◈",
        "members": ["Hayami Amamiya", "Shaye Kaylen", "Shiina Ishioka", "Theresa Felix"],
        "mbti_types": ["ISTP", "ESTP", "ISFP", "ESFP"],
        "tagline": "If something exploded, statistically an Explorer was nearby.",
        "facts": [
            "The most physically comfortable around each other. Zero personal space rules.",
            "They tease the Analysts relentlessly for overthinking oxygen.",
            "Shaye and Theresa absolutely escalate things just to see who reacts first.",
            "Hayami pretends they don't enjoy the chaos. They do. They just won't admit it.",
            "Collectively they have the highest real-world practical intelligence in any room.",
        ],
        "strengths": "Adaptability, physical instinct, real-time decision making",
        "weakness": "Long-term planning, sitting still for more than five minutes",
        "chaos_rating": "9 / 10 — Kinetic. Inevitable. Somehow fine.",
    },
    "Sentinels": {
        "color": "#20cbff",
        "icon": "◉",
        "members": ["Chiyo Funai", "Shizuka Aikawa", "Mayumi Sasaki", "Lily Raven"],
        "mbti_types": ["ISTJ", "ESTJ", "ISFJ", "ESFJ"],
        "tagline": "They look the most stable as a unit. They are not.",
        "facts": [
            "Silent competitions happen constantly — discipline, control, composure.",
            "Mayumi is the emotional stabilizer whether she likes it or not.",
            "Shizuka and Gillian have mutual 'we could conquer things together' energy and it terrifies everyone.",
            "If rules exist, Chiyo enforces them. If rules don't exist, Shizuka writes them.",
            "Collectively the most durable group in a sustained fight.",
        ],
        "strengths": "Defense, endurance, group coordination, rule enforcement",
        "weakness": "Flexibility, handling genuine chaos, admitting internal tension",
        "chaos_rating": "5 / 10 — Structured chaos. Nobody talks about it.",
    },
    "Diplomats": {
        "color": "#12ff1e",
        "icon": "◇",
        "members": ["Sonia Spade", "Himiko Nakayama", "Katie Olson", "Emily Caddel"],
        "mbti_types": ["INFJ", "ENFJ", "INFP", "ENFP"],
        "tagline": "The most emotionally dangerous group in a quiet room.",
        "facts": [
            "Sonia knows things she does not say. This unsettles everyone including her own group.",
            "Himiko unintentionally collects people like side quests.",
            "Katie absorbs group tension like a sponge and then pretends she's fine.",
            "Emily will start three bonding activities at once and finish none of them.",
            "The only group that could emotionally dismantle everyone if they wanted to.",
        ],
        "strengths": "Emotional intelligence, influence, long-game manipulation, inspiration",
        "weakness": "Cold strategy, direct confrontation, pretending everything is fine",
        "chaos_rating": "7 / 10 — Quiet chaos. The dangerous kind.",
    },
}

cross_group_dynamics = [
    ("Analysts + Explorers", "#89b4fa", "'Let's test it' meets 'Let's just do it'. Somehow works disturbingly well."),
    ("Sentinels + Diplomats", "#f38ba8", "Structured order meets emotional influence. Could stabilize the world or soft-launch a political coup."),
    ("Analysts vs Explorers", "#a6e3a1", "Explorers think Analysts are dramatic. Analysts think Explorers are reckless. Both are correct."),
    ("Diplomats vs Everyone", "#cba6f7", "The only group that can calm everyone down. Also the only group that could emotionally dismantle everyone."),
]