relationships = {
    ("paula", "mica"): "Intellectual rivals. They argue like it's foreplay. Neither admits they enjoy it.",
    ("paula", "hiromi"): "Mutual respect. Compete silently over who predicts outcomes better.",
    ("paula", "gillian"): "Paula finds her too forceful. Gillian thinks Paula hides behind theory.",
    ("paula", "hayami"): "Fascination bordering on obsession. Paula calls it research. It is not just research.",
    ("paula", "shaye"): "Paula finds them inefficient. Secretly intrigued by their momentum logic.",
    ("paula", "shiina"): "Paula thinks she's deceptively dangerous. Approaches carefully.",
    ("paula", "theresa"): "Overstimulating. Paula avoids her field on purpose.",
    ("paula", "chiyo"): "Paula appreciates her discipline. Trusts her consistency.",
    ("paula", "shizuka"): "Too loud, too direct. Tension.",
    ("paula", "mayumi"): "Paula's protective instinct triggered. She doesn't know why.",
    ("paula", "lily"): "Overfriendly. Paula is suspicious of her emotional access.",
    ("paula", "sonia"): "Paula is uneasy. Sonia reads her too well.",
    ("paula", "himiko"): "Paula sees the dominance structure immediately. Watches from a distance.",
    ("paula", "katie"): "Paula finds her emotionally unpredictable. Studies her like a phenomenon.",
    ("paula", "emily"): "Paula is simultaneously impressed and exhausted by her brain.",
    ("mica", "hiromi"): "Strategic chess match energy. Mutual mental sparring.",
    ("mica", "gillian"): "Power clash. Both want to dominate the room.",
    ("mica", "hayami"): "Mica wants to crack their calm exterior. Possibly flirting. Possibly experimentation.",
    ("mica", "shaye"): "High-energy chaos duo. Dangerous together.",
    ("mica", "shiina"): "Mica respects her quiet depth. Doesn't tease her much.",
    ("mica", "theresa"): "Playful rivalry. Sensory field vs adaptation.",
    ("mica", "chiyo"): "Mica tries to get a rise out of her. Rarely succeeds.",
    ("mica", "shizuka"): "Competitive. Neither backs down.",
    ("mica", "mayumi"): "Mica has a soft spot. Doesn't admit it.",
    ("mica", "lily"): "Mica is amused by her social tactics.",
    ("mica", "sonia"): "Mica is slightly wary. Doesn't like when someone sees through her.",
    ("mica", "himiko"): "Power recognizes power. Dangerous tension.",
    ("mica", "katie"): "Mica is curious about her emotional volatility.",
    ("mica", "emily"): "Chaotic idea synergy. The room cannot contain them.",
    ("hiromi", "gillian"): "Mutual strategic admiration.",
    ("hiromi", "hayami"): "Mutual respect. Tactical minds. Conversations feel like chess moves.",
    ("hiromi", "shaye"): "Hiromi finds them predictable in long games.",
    ("hiromi", "shiina"): "Hiromi underestimates her at first. Regrets it.",
    ("hiromi", "theresa"): "Hiromi is annoyed by sensory interference.",
    ("hiromi", "chiyo"): "Reliable asset. Clean efficient conversations.",
    ("hiromi", "shizuka"): "Could lead together. Might clash.",
    ("hiromi", "mayumi"): "Hiromi respects her restraint deeply.",
    ("hiromi", "lily"): "Too emotionally loud for Hiromi.",
    ("hiromi", "sonia"): "Intrigued. Possible intellectual equals.",
    ("hiromi", "himiko"): "Hiromi watches her leadership style critically.",
    ("hiromi", "katie"): "Hiromi thinks she burns too brightly emotionally.",
    ("hiromi", "emily"): "Hiromi finds her scattered but unexpectedly insightful.",
    ("gillian", "hayami"): "Gillian wants to test them physically. They don't mind proving a point.",
    ("gillian", "shaye"): "Gillian respects their aggression. Direct power rivalry.",
    ("gillian", "shiina"): "Gillian finds her too subtle.",
    ("gillian", "theresa"): "Gillian finds her disruptive.",
    ("gillian", "chiyo"): "Gillian trusts her discipline.",
    ("gillian", "shizuka"): "Mutual 'we could rule' vibe. Scary combo.",
    ("gillian", "mayumi"): "Gillian's protective instinct kicks in.",
    ("gillian", "lily"): "Gillian thinks she's too socially soft.",
    ("gillian", "sonia"): "Gillian doesn't like emotional manipulation.",
    ("gillian", "himiko"): "Leadership tension.",
    ("gillian", "katie"): "Gillian is unsure how to approach her volatility.",
    ("gillian", "emily"): "Gillian finds her unfocused but energetic.",
    ("hayami", "shaye"): "Competitive sibling energy. Physical sparring is inevitable.",
    ("hayami", "shiina"): "Silent understanding. No need for many words.",
    ("hayami", "theresa"): "Theresa invades their space constantly. Hayami tolerates it more than they admit.",
    ("hayami", "chiyo"): "Efficiency alliance. Very little drama.",
    ("hayami", "shizuka"): "Authority clash. Hayami doesn't like being commanded.",
    ("hayami", "mayumi"): "Hayami's protective instinct triggered. They're gentler around her.",
    ("hayami", "lily"): "Lily tries to open them up. Hayami resists. Softly.",
    ("hayami", "sonia"): "Sonia reads them too well. That's mildly irritating.",
    ("hayami", "himiko"): "Himiko tries to inspire them. Hayami prefers autonomy. Intriguing dynamic.",
    ("hayami", "katie"): "Katie's emotional intensity unsettles them. But they don't pull away.",
    ("hayami", "emily"): "Emily drags them into spontaneous nonsense. Hayami complains. Shows up anyway.",
    ("shaye", "shiina"): "Shaye is surprised by how deep she is.",
    ("shaye", "theresa"): "Adrenaline besties. Probably bad influences on each other.",
    ("shaye", "chiyo"): "Shaye thinks she's too rigid. Teases her.",
    ("shaye", "shizuka"): "Explosive confrontations waiting to happen.",
    ("shaye", "mayumi"): "Shaye softens around her. Doesn't advertise it.",
    ("shaye", "lily"): "Lily keeps trying to civilize them. Mild success.",
    ("shaye", "sonia"): "Shaye doesn't trust the emotional insight thing.",
    ("shaye", "himiko"): "Shaye feels challenged by her leadership attempts.",
    ("shaye", "katie"): "Shaye's protective energy activated.",
    ("shaye", "emily"): "Spontaneous duo energy. Things get chaotic fast.",
    ("shiina", "theresa"): "Shiina feels safe with her energy.",
    ("shiina", "chiyo"): "Mutual quiet reliability.",
    ("shiina", "shizuka"): "Power tension. Shiina avoids direct clash.",
    ("shiina", "mayumi"): "Emotional sanctuary for each other.",
    ("shiina", "lily"): "Shiina appreciates her warmth.",
    ("shiina", "sonia"): "Deep wordless conversations.",
    ("shiina", "himiko"): "Shiina feels seen and supported.",
    ("shiina", "katie"): "Kindred spirits.",
    ("shiina", "emily"): "Emily encourages her creativity.",
    ("theresa", "chiyo"): "Theresa teases her seriousness.",
    ("theresa", "shizuka"): "Competitive sparks.",
    ("theresa", "mayumi"): "Gentle affection.",
    ("theresa", "lily"): "Social butterfly synchronization.",
    ("theresa", "sonia"): "Theresa tries to pull her out of introspection.",
    ("theresa", "himiko"): "Theresa admires her leadership energy.",
    ("theresa", "katie"): "Theresa wants to cheer her up constantly.",
    ("theresa", "emily"): "Double sparkle chaos. No brakes.",
    ("chiyo", "shizuka"): "Power structure alignment... until authority overlaps.",
    ("chiyo", "mayumi"): "Deep trust. Chiyo relaxes around her.",
    ("chiyo", "lily"): "Chiyo appreciates her social smoothing efforts.",
    ("chiyo", "sonia"): "Slight unease. Sonia notices what Chiyo suppresses.",
    ("chiyo", "himiko"): "Chiyo respects her leadership but doesn't follow blindly.",
    ("chiyo", "katie"): "Chiyo is gentle with her. Avoids overwhelming her.",
    ("chiyo", "emily"): "Chiyo thinks she's chaotic. Secretly amused.",
    ("shizuka", "mayumi"): "Shizuka is protective but unintentionally intimidating.",
    ("shizuka", "lily"): "Shizuka appreciates her diplomacy but thinks she's too soft.",
    ("shizuka", "sonia"): "Shizuka distrusts emotional manipulation.",
    ("shizuka", "himiko"): "Leadership rivalry simmering. The rivalry that could destabilize a city.",
    ("shizuka", "katie"): "Shizuka doesn't quite understand her emotional volatility.",
    ("shizuka", "emily"): "Shizuka finds her scattered but tolerable.",
    ("mayumi", "lily"): "Socially supportive duo. Comfort pair. Quiet bonding.",
    ("mayumi", "sonia"): "Deep empathy resonance.",
    ("mayumi", "himiko"): "Mayumi is inspired by her leadership.",
    ("mayumi", "katie"): "Fierce mutual protection.",
    ("mayumi", "emily"): "Emily encourages her to step out of her shell.",
    ("lily", "sonia"): "Deep emotional discussions. Lily appreciates her warmth but Sonia doesn't open fully.",
    ("lily", "himiko"): "Powerful social duo.",
    ("lily", "katie"): "Lily overflows her with affection. Protective warmth.",
    ("lily", "emily"): "Social amplification mode activated.",
    ("sonia", "himiko"): "Mutual recognition of influence. Soft power meets overt charisma.",
    ("sonia", "katie"): "Soul-level conversations at 2AM.",
    ("sonia", "emily"): "Sonia is amused by her brightness. Grounds her when needed.",
    ("himiko", "katie"): "Himiko wants to shield her from self-doubt.",
    ("himiko", "emily"): "Himiko encourages her big visions.",
    ("katie", "emily"): "Chaotic dreamer duo. Dreamscape partnership.",
}

def get_relationship(c1,c2):
    pair = tuple(sorted([c1,c2]))
    reverse = (pair[1], pair[0])
    if pair in relationships:
        return relationships[pair]
    elif reverse in relationships:
        return relationships[reverse]
    return None